# Generated by Django 5.2.17 on 2026-09-20 07:33

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_project_key_prefix'),
        ('codebase', '0003_alter_commitfile_patch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('similar', 'Similar'), ('duplicate', 'Duplicate'), ('caused_by', 'Caused by'), ('blocks', 'Blocks')], max_length=16)),
                ('confidence', models.FloatField(default=1.0)),
                ('source', models.CharField(default='manual', max_length=16)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BugRequirementLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('inferred', 'Inferred from data'), ('ai', 'AI suggested')], default='manual', max_length=16)),
                ('confidence', models.FloatField(default=1.0)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BugTestCaseLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('inferred', 'Inferred from data'), ('ai', 'AI suggested')], default='manual', max_length=16)),
                ('confidence', models.FloatField(default=1.0)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('s1', 'S1 - Blocker'), ('s2', 'S2 - Critical'), ('s3', 'S3 - Major'), ('s4', 'S4 - Minor')], default='s3', max_length=4)),
                ('priority', models.CharField(choices=[('p0', 'P0 - Critical'), ('p1', 'P1 - High'), ('p2', 'P2 - Medium'), ('p3', 'P3 - Low')], default='p2', max_length=4)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('reopened', 'Reopened')], default='open', max_length=16)),
                ('error_type', models.CharField(blank=True, default='', max_length=200)),
                ('stack_trace', models.TextField(blank=True, default='')),
                ('environment', models.CharField(blank=True, default='', max_length=100)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('occurrence_count', models.PositiveIntegerField(default=0)),
                ('summary_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bugs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='accounts.project')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_bugs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BugCommitLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('inferred', 'Inferred from data'), ('ai', 'AI suggested')], default='manual', max_length=16)),
                ('confidence', models.FloatField(default=1.0)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit_links', to='bugs.bug')),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_links', to='codebase.commit')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BugModuleLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('inferred', 'Inferred from data'), ('ai', 'AI suggested')], default='manual', max_length=16)),
                ('confidence', models.FloatField(default=1.0)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_links', to='bugs.bug')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_links', to='codebase.module')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BugOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seen_at', models.DateTimeField(db_index=True)),
                ('environment', models.CharField(blank=True, default='', max_length=100)),
                ('count', models.PositiveIntegerField(default=1)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='bugs.bug')),
            ],
            options={
                'ordering': ('-seen_at',),
                'abstract': False,
            },
        ),
    ]
