# Generated by Django 5.2.17 on 2026-09-20 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bugs', '0002_initial'),
        ('requirements', '0001_initial'),
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugoccurrence',
            name='test_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_occurrences', to='testing.testrun'),
        ),
        migrations.AddField(
            model_name='bugrelation',
            name='bug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='bugs.bug'),
        ),
        migrations.AddField(
            model_name='bugrelation',
            name='related_bug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='bugs.bug'),
        ),
        migrations.AddField(
            model_name='bugrequirementlink',
            name='bug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_links', to='bugs.bug'),
        ),
        migrations.AddField(
            model_name='bugrequirementlink',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_links', to='requirements.requirement'),
        ),
        migrations.AddField(
            model_name='bugtestcaselink',
            name='bug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_links', to='bugs.bug'),
        ),
        migrations.AddField(
            model_name='bugtestcaselink',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_links', to='testing.testcase'),
        ),
        migrations.AddConstraint(
            model_name='bug',
            constraint=models.UniqueConstraint(fields=('project', 'key'), name='uniq_bug_project_key'),
        ),
        migrations.AddConstraint(
            model_name='bugcommitlink',
            constraint=models.UniqueConstraint(fields=('bug', 'commit'), name='uniq_bug_commit_link'),
        ),
        migrations.AddConstraint(
            model_name='bugmodulelink',
            constraint=models.UniqueConstraint(fields=('bug', 'module'), name='uniq_bug_module_link'),
        ),
        migrations.AddConstraint(
            model_name='bugrelation',
            constraint=models.UniqueConstraint(fields=('bug', 'related_bug', 'kind'), name='uniq_bug_relation'),
        ),
        migrations.AddConstraint(
            model_name='bugrelation',
            constraint=models.CheckConstraint(condition=models.Q(('bug', models.F('related_bug')), _negated=True), name='bug_relation_not_self'),
        ),
        migrations.AddConstraint(
            model_name='bugrequirementlink',
            constraint=models.UniqueConstraint(fields=('bug', 'requirement'), name='uniq_bug_requirement_link'),
        ),
        migrations.AddConstraint(
            model_name='bugtestcaselink',
            constraint=models.UniqueConstraint(fields=('bug', 'test_case'), name='uniq_bug_testcase_link'),
        ),
    ]
