# Generated by Django 5.2.17 on 2026-09-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugrelation',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('inferred', 'Inferred from data'), ('ai', 'AI suggested')], default='manual', max_length=16),
        ),
    ]
