# Generated by Django 5.2.17 on 2026-09-29 03:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_project_key_prefix'),
        ('bugs', '0004_alter_bugrelation_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['project', 'status'], name='idx_bug_project_status'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['project', 'severity'], name='idx_bug_project_severity'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['project', '-last_seen_at'], name='idx_bug_project_lastseen'),
        ),
    ]
