# Generated by Django 5.2.17 on 2026-09-20 07:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_project_key_prefix'),
        ('codebase', '0003_alter_commitfile_patch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('released', 'Released'), ('rolled_back', 'Rolled back')], default='planned', max_length=16)),
                ('planned_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='accounts.project')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReleaseCommitLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('inferred', 'Inferred from data'), ('ai', 'AI suggested')], default='manual', max_length=16)),
                ('confidence', models.FloatField(default=1.0)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_links', to='codebase.commit')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit_links', to='releases.release')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReleaseRiskSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(default=0.0)),
                ('level', models.CharField(default='low', max_length=16)),
                ('breakdown', models.JSONField(blank=True, default=list)),
                ('computed_at', models.DateTimeField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_snapshots', to='releases.release')),
            ],
            options={
                'ordering': ('-computed_at',),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='release',
            constraint=models.UniqueConstraint(fields=('project', 'version'), name='uniq_release_project_version'),
        ),
        migrations.AddConstraint(
            model_name='releasecommitlink',
            constraint=models.UniqueConstraint(fields=('release', 'commit'), name='uniq_release_commit_link'),
        ),
    ]
