# Generated by Django 5.2.17 on 2026-09-29 03:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_project_key_prefix'),
        ('releases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['project', 'status'], name='idx_release_project_status'),
        ),
    ]
