# Generated by Django 5.2.17 on 2026-09-29 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_release_idx_release_project_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReleaseRiskSnapshot',
        ),
    ]
