# Generated by Django 5.2.17 on 2026-09-20 07:33

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # The `embedding` column below is `vector(1536)`, so the extension has to exist
        # first. This edge is not derivable from the models, which is exactly why a
        # pristine database needs it spelled out: without it the extension is created
        # whenever the graph happens to reach its own leaf, which is *after* this table.
        ('core', '0001_enable_pgvector'),
        ('accounts', '0002_alter_project_key_prefix'),
        ('codebase', '0004_commit_requirement'),
        ('requirements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_rate', models.FloatField(default=0.0)),
                ('branch_rate', models.FloatField(default=0.0)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('captured_at', models.DateTimeField()),
                ('commit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coverage_snapshots', to='codebase.commit')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coverage_snapshots', to='codebase.module')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_snapshots', to='accounts.project')),
            ],
            options={
                'ordering': ('-captured_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=500)),
                ('precondition', models.TextField(blank=True, default='')),
                ('expected', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('p0', 'P0 - Critical'), ('p1', 'P1 - High'), ('p2', 'P2 - Medium'), ('p3', 'P3 - Low')], default='p2', max_length=4)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('automation', models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('ui', 'UI'), ('unit', 'Unit')], default='manual', max_length=16)),
                ('automation_suggestion', models.JSONField(blank=True, default=dict)),
                ('origin', models.CharField(choices=[('manual', 'Written by hand'), ('ai_generated', 'Suggested by AI')], default='manual', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('deprecated', 'Deprecated')], default='active', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='accounts.project')),
            ],
            options={
                'ordering': ('key',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestCaseCommitLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('inferred', 'Inferred from data'), ('ai', 'AI suggested')], default='manual', max_length=16)),
                ('confidence', models.FloatField(default=1.0)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_links', to='codebase.commit')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit_links', to='testing.testcase')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestCaseModuleLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('inferred', 'Inferred from data'), ('ai', 'AI suggested')], default='manual', max_length=16)),
                ('confidence', models.FloatField(default=1.0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_links', to='codebase.module')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_links', to='testing.testcase')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestCaseRequirementLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('inferred', 'Inferred from data'), ('ai', 'AI suggested')], default='manual', max_length=16)),
                ('confidence', models.FloatField(default=1.0)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_links', to='requirements.requirement')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_links', to='testing.testcase')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestCaseStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seq', models.PositiveSmallIntegerField(default=1)),
                ('action', models.TextField()),
                ('test_data', models.JSONField(blank=True, default=dict)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='testing.testcase')),
            ],
            options={
                'ordering': ('test_case', 'seq'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.CharField(blank=True, default='', max_length=100)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('ci', 'CI'), ('ai', 'Triggered by AI')], default='manual', max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('aborted', 'Aborted')], default='queued', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('passed', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('commit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_runs', to='codebase.commit')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='accounts.project')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_key', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('error', 'Errored')], max_length=16)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('stack_trace', models.TextField(blank=True, default='')),
                ('attachments', models.JSONField(blank=True, default=dict)),
                ('test_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='testing.testcase')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='testing.testrun')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('regression', 'Regression'), ('smoke', 'Smoke'), ('full', 'Full'), ('module', 'Module')], default='regression', max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_suites', to='accounts.project')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='testrun',
            name='suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='testing.testsuite'),
        ),
        migrations.CreateModel(
            name='TestSuiteCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seq', models.PositiveSmallIntegerField(default=1)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suite_cases', to='testing.testsuite')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suite_cases', to='testing.testcase')),
            ],
            options={
                'ordering': ('suite', 'seq'),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='testcase',
            constraint=models.UniqueConstraint(fields=('project', 'key'), name='uniq_testcase_project_key'),
        ),
        migrations.AddConstraint(
            model_name='testcasecommitlink',
            constraint=models.UniqueConstraint(fields=('test_case', 'commit'), name='uniq_testcase_commit_link'),
        ),
        migrations.AddConstraint(
            model_name='testcasemodulelink',
            constraint=models.UniqueConstraint(fields=('test_case', 'module'), name='uniq_testcase_module_link'),
        ),
        migrations.AddConstraint(
            model_name='testcaserequirementlink',
            constraint=models.UniqueConstraint(fields=('test_case', 'requirement'), name='uniq_testcase_requirement_link'),
        ),
        migrations.AddConstraint(
            model_name='testcasestep',
            constraint=models.UniqueConstraint(fields=('test_case', 'seq'), name='uniq_testcase_step_seq'),
        ),
        migrations.AddConstraint(
            model_name='testsuite',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_testsuite_project_name'),
        ),
        migrations.AddConstraint(
            model_name='testsuitecase',
            constraint=models.UniqueConstraint(fields=('suite', 'test_case'), name='uniq_testsuite_case'),
        ),
    ]
