# Generated by Django 5.2.17 on 2026-09-29 03:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_project_key_prefix'),
        ('codebase', '0004_commit_requirement'),
        ('testing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coveragesnapshot',
            index=models.Index(fields=['module', '-captured_at'], name='idx_coverage_module_captured'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['project', 'status'], name='idx_testcase_project_status'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['status'], name='idx_testresult_status'),
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['project', 'status'], name='idx_testrun_project_status'),
        ),
    ]
