# Generated by Django 5.2.17 on 2026-09-20 07:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('head_sha', models.CharField(blank=True, default='', max_length=64)),
                ('is_default', models.BooleanField(default=False)),
                ('is_protected', models.BooleanField(default=False)),
                ('last_commit_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sha', models.CharField(max_length=64)),
                ('parent_shas', models.JSONField(blank=True, default=list)),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('author_email', models.CharField(blank=True, default='', max_length=320)),
                ('committer_email', models.CharField(blank=True, default='', max_length=320)),
                ('message', models.TextField(blank=True, default='')),
                ('committed_at', models.DateTimeField(db_index=True)),
                ('additions', models.PositiveIntegerField(default=0)),
                ('deletions', models.PositiveIntegerField(default=0)),
                ('files_changed', models.PositiveIntegerField(default=0)),
                ('pull_request_external_id', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'ordering': ('-committed_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommitFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=1024)),
                ('old_path', models.CharField(blank=True, default='', max_length=1024)),
                ('change_type', models.CharField(choices=[('add', 'Added'), ('modify', 'Modified'), ('delete', 'Deleted'), ('rename', 'Renamed')], max_length=16)),
                ('additions', models.PositiveIntegerField(default=0)),
                ('deletions', models.PositiveIntegerField(default=0)),
                ('patch', models.TextField(blank=True, null=True)),
                ('has_patch', models.BooleanField(default=False)),
                ('truncated', models.BooleanField(default=False)),
                ('language', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'ordering': ('path',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommitModuleImpact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('churn_lines', models.PositiveIntegerField(default=0)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('weight', models.FloatField(default=0.0)),
                ('is_test_change', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('package', 'Package'), ('module', 'Module'), ('service', 'Service'), ('dir', 'Directory')], default='module', max_length=16)),
                ('path_prefix', models.CharField(max_length=512)),
                ('language', models.CharField(blank=True, default='', max_length=32)),
                ('centrality_score', models.FloatField(default=0.0)),
                ('owner_team', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ('path_prefix',),
                'abstract': False,
            },
        ),
    ]
