# Generated by Django 5.2.17 on 2026-09-20 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_project_key_prefix'),
        ('codebase', '0001_initial'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='integrations.repository'),
        ),
        migrations.AddField(
            model_name='commit',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='integrations.repository'),
        ),
        migrations.AddField(
            model_name='commitfile',
            name='commit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='codebase.commit'),
        ),
        migrations.AddField(
            model_name='commitmoduleimpact',
            name='commit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_impacts', to='codebase.commit'),
        ),
        migrations.AddField(
            model_name='module',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='accounts.project'),
        ),
        migrations.AddField(
            model_name='commitmoduleimpact',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit_impacts', to='codebase.module'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('repository', 'name'), name='uniq_branch_repo_name'),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['repository', 'committed_at'], name='idx_commit_repo_when'),
        ),
        migrations.AddConstraint(
            model_name='commit',
            constraint=models.UniqueConstraint(fields=('repository', 'sha'), name='uniq_commit_repo_sha'),
        ),
        migrations.AddIndex(
            model_name='commitfile',
            index=models.Index(fields=['commit', 'path'], name='idx_commitfile_commit_path'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('project', 'path_prefix'), name='uniq_module_project_path_prefix'),
        ),
        migrations.AddConstraint(
            model_name='commitmoduleimpact',
            constraint=models.UniqueConstraint(fields=('commit', 'module'), name='uniq_commit_module_impact'),
        ),
    ]
