# Generated by Django 5.2.17 on 2026-09-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebase', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitfile',
            name='patch',
            field=models.TextField(blank=True, default=''),
        ),
    ]
