# Generated by Django 5.2.17 on 2026-09-20 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebase', '0003_alter_commitfile_patch'),
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commits', to='requirements.requirement'),
        ),
    ]
