# Generated by Django 5.2.17 on 2026-09-20 08:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_project_key_prefix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('weight', models.FloatField()),
                ('enabled', models.BooleanField(default=True)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_rules', to='accounts.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_rules', to='accounts.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('code',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('project', 'code'), name='uniq_risk_rule_project_code'), models.UniqueConstraint(condition=models.Q(('org__isnull', False), ('project__isnull', True)), fields=('org', 'code'), name='uniq_risk_rule_org_code'), models.UniqueConstraint(condition=models.Q(('org__isnull', True), ('project__isnull', True)), fields=('code',), name='uniq_risk_rule_default_code'), models.CheckConstraint(condition=models.Q(('weight__gte', 0)), name='risk_rule_weight_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_type', models.CharField(choices=[('commit', 'Commit'), ('module', 'Module'), ('release', 'Release'), ('project', 'Project')], max_length=16)),
                ('subject_id', models.CharField(max_length=64)),
                ('score', models.FloatField()),
                ('level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=16)),
                ('breakdown', models.JSONField(blank=True, default=list)),
                ('computed_at', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='accounts.project')),
            ],
            options={
                'ordering': ('-computed_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['project', 'subject_type', 'subject_id', '-computed_at'], name='idx_riskscore_lookup')],
            },
        ),
    ]
