# Generated by Django 5.2.17 on 2026-09-29 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskrule',
            name='params',
        ),
        migrations.DeleteModel(
            name='RiskScore',
        ),
    ]
