# Generated by Django 5.2.17 on 2026-09-20 07:53

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_project_key_prefix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_code', models.CharField(max_length=64)),
                ('target_type', models.CharField(blank=True, default='', max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('progress', models.FloatField(default=0.0)),
                ('error', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, default=dict)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=120)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to='accounts.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIAnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('provider_type', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=120)),
                ('capability', models.CharField(default='chat', max_length=32)),
                ('prompt_id', models.CharField(blank=True, default='', max_length=64)),
                ('prompt_version', models.PositiveSmallIntegerField(default=0)),
                ('input_digest', models.CharField(blank=True, default='', max_length=64)),
                ('input_text', models.TextField(blank=True, default='')),
                ('input_truncated', models.BooleanField(default=False)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cached_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('output_text', models.TextField(blank=True, default='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ai.aianalysisjob')),
            ],
            options={
                'ordering': ('job', 'sequence'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIModelPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_type', models.CharField(choices=[('openai', 'OpenAI'), ('deepseek', 'DeepSeek'), ('qwen', 'Qwen'), ('ollama', 'Ollama'), ('openai_compatible', 'OpenAI-compatible')], max_length=32)),
                ('model', models.CharField(max_length=120)),
                ('input_per_1k', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('output_per_1k', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('cached_input_per_1k', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('embedding_per_1k', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('effective_from', models.DateTimeField()),
            ],
            options={
                'ordering': ('-effective_from',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('provider_type', 'model', 'effective_from'), name='uniq_ai_pricing_provider_model_from')],
            },
        ),
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_type', models.CharField(choices=[('openai', 'OpenAI'), ('deepseek', 'DeepSeek'), ('qwen', 'Qwen'), ('ollama', 'Ollama'), ('openai_compatible', 'OpenAI-compatible')], max_length=32)),
                ('label', models.CharField(max_length=100)),
                ('base_url', models.URLField(blank=True, default='')),
                ('api_key', apps.core.models.EncryptedTextField(blank=True, default='')),
                ('capability_models', models.JSONField(blank=True, default=dict)),
                ('embedding_dim', models.PositiveIntegerField(default=1536)),
                ('is_default', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('invalid', 'Invalid credentials'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_providers', to='accounts.organization')),
            ],
            options={
                'ordering': ('label',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIToolCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('tool_name', models.CharField(max_length=64)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ok', 'Ok'), ('error', 'Error'), ('denied', 'Denied')], max_length=16)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('scope_denied', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='ai.aianalysisrun')),
            ],
            options={
                'ordering': ('run', 'sequence'),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='aianalysisjob',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('project', 'idempotency_key'), name='uniq_ai_job_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='aianalysisrun',
            constraint=models.UniqueConstraint(fields=('job', 'sequence'), name='uniq_ai_run_job_sequence'),
        ),
        migrations.AddConstraint(
            model_name='aiproviderconfig',
            constraint=models.UniqueConstraint(fields=('org', 'label'), name='uniq_ai_provider_org_label'),
        ),
        migrations.AddConstraint(
            model_name='aitoolcall',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='uniq_ai_tool_call_run_sequence'),
        ),
    ]
