# Generated by Django 5.2.17 on 2026-09-20 08:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_project_key_prefix'),
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_code', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=0.0)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('dismissed', 'Dismissed'), ('converted', 'Converted into work')], default='new', max_length=16)),
                ('dedupe_hash', models.CharField(blank=True, default='', max_length=64)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='ai.aianalysisjob')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_findings', to='accounts.project')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_hash', ''), _negated=True), fields=('project', 'dedupe_hash'), name='uniq_ai_finding_dedupe')],
            },
        ),
    ]
