# Generated by Django 5.2.17 on 2026-09-29 03:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_project_key_prefix'),
        ('ai', '0003_airecommendation_aiconfirmation_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aianalysisjob',
            index=models.Index(fields=['project', 'status'], name='idx_aijob_project_status'),
        ),
        migrations.AddIndex(
            model_name='aifinding',
            index=models.Index(fields=['project', 'status'], name='idx_aifinding_project_status'),
        ),
        migrations.AddIndex(
            model_name='aifinding',
            index=models.Index(fields=['project', 'severity'], name='idx_aifinding_project_severity'),
        ),
        migrations.AddIndex(
            model_name='airecommendation',
            index=models.Index(fields=['project', 'status'], name='idx_airec_project_status'),
        ),
    ]
