# Generated by Django 5.2.17 on 2026-09-20 07:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_project_key_prefix'),
        ('codebase', '0003_alter_commitfile_patch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_key', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('manual', 'Entered by hand'), ('jira', 'Issue tracker'), ('document', 'Document'), ('imported', 'Imported')], default='manual', max_length=16)),
                ('source_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('in_progress', 'In progress'), ('implemented', 'Implemented'), ('verified', 'Verified'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('priority', models.CharField(choices=[('p0', 'P0 - Critical'), ('p1', 'P1 - High'), ('p2', 'P2 - Medium'), ('p3', 'P3 - Low')], default='p2', max_length=4)),
                ('sprint', models.CharField(blank=True, default='', max_length=100)),
                ('acceptance_criteria', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='accounts.project')),
            ],
            options={
                'ordering': ('external_key',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModuleRequirementLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('inferred', 'Inferred from data'), ('ai', 'AI suggested')], default='manual', max_length=16)),
                ('confidence', models.FloatField(default=1.0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_links', to='codebase.module')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_links', to='requirements.requirement')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequirementItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seq', models.PositiveSmallIntegerField(default=1)),
                ('type', models.CharField(choices=[('scenario', 'Scenario'), ('constraint', 'Constraint'), ('edge_case', 'Edge case'), ('acceptance', 'Acceptance criterion')], default='scenario', max_length=16)),
                ('text', models.TextField()),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='requirements.requirement')),
            ],
            options={
                'ordering': ('requirement', 'seq'),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.UniqueConstraint(fields=('project', 'external_key'), name='uniq_requirement_project_key'),
        ),
        migrations.AddConstraint(
            model_name='modulerequirementlink',
            constraint=models.UniqueConstraint(fields=('requirement', 'module'), name='uniq_module_requirement_link'),
        ),
        migrations.AddConstraint(
            model_name='requirementitem',
            constraint=models.UniqueConstraint(fields=('requirement', 'seq'), name='uniq_requirement_item_seq'),
        ),
    ]
