# Generated by Django 5.2.17 on 2026-09-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='key_prefix',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
