# Generated by Django 5.2.17 on 2026-09-20 07:10

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_project_key_prefix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab')], default='github', max_length=32)),
                ('auth_type', models.CharField(choices=[('pat', 'Personal access token'), ('oauth', 'OAuth'), ('app', 'App installation')], default='pat', max_length=32)),
                ('label', models.CharField(max_length=100)),
                ('base_url', models.URLField(blank=True, default='')),
                ('token', apps.core.models.EncryptedTextField(blank=True, default='')),
                ('webhook_secret', apps.core.models.EncryptedTextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('invalid', 'Invalid credentials')], default='active', max_length=32)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_connections', to='accounts.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='git_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('label',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab')], default='github', max_length=32)),
                ('external_id', models.CharField(max_length=64)),
                ('full_name', models.CharField(max_length=255)),
                ('default_branch', models.CharField(default='main', max_length=255)),
                ('is_private', models.BooleanField(default=False)),
                ('sync_status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='idle', max_length=32)),
                ('sync_cursor', models.JSONField(blank=True, default=dict)),
                ('sync_window_days', models.PositiveIntegerField(default=90)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True, default='')),
                ('module_depth', models.PositiveSmallIntegerField(default=2)),
                ('module_overrides', models.JSONField(blank=True, default=dict, help_text='Path prefix -> module name.')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repositories', to='integrations.gitconnection')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='accounts.project')),
            ],
            options={
                'ordering': ('full_name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_id', models.CharField(max_length=100, unique=True)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='integrations.gitconnection')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='gitconnection',
            constraint=models.UniqueConstraint(fields=('org', 'label'), name='uniq_git_connection_org_label'),
        ),
        migrations.AddConstraint(
            model_name='repository',
            constraint=models.UniqueConstraint(fields=('project', 'external_id'), name='uniq_repository_project_external_id'),
        ),
    ]
